services:
  - type: web
    name: snake-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
    scaling:
      minInstances: 0
      maxInstances: 1